//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACST.AWS.TextractViewer.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public int ZoomInitialValue {
            get {
                return ((int)(this["ZoomInitialValue"]));
            }
            set {
                this["ZoomInitialValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SaveSettingsOnExit {
            get {
                return ((bool)(this["SaveSettingsOnExit"]));
            }
            set {
                this["SaveSettingsOnExit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CenterParent")]
        public global::System.Windows.Forms.FormStartPosition StartPosition {
            get {
                return ((global::System.Windows.Forms.FormStartPosition)(this["StartPosition"]));
            }
            set {
                this["StartPosition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public global::System.Windows.Forms.FormWindowState WindowsState {
            get {
                return ((global::System.Windows.Forms.FormWindowState)(this["WindowsState"]));
            }
            set {
                this["WindowsState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 37")]
        public global::System.Drawing.Point WindowsLocation {
            get {
                return ((global::System.Drawing.Point)(this["WindowsLocation"]));
            }
            set {
                this["WindowsLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2000, 1400")]
        public global::System.Drawing.Size MinimumSize {
            get {
                return ((global::System.Drawing.Size)(this["MinimumSize"]));
            }
            set {
                this["MinimumSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ConfirmationSaveChoice {
            get {
                return ((bool)(this["ConfirmationSaveChoice"]));
            }
            set {
                this["ConfirmationSaveChoice"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ConfirmationSaveAndExport {
            get {
                return ((bool)(this["ConfirmationSaveAndExport"]));
            }
            set {
                this["ConfirmationSaveAndExport"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool HighlightOnTab {
            get {
                return ((bool)(this["HighlightOnTab"]));
            }
            set {
                this["HighlightOnTab"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowSaveConfirmation {
            get {
                return ((bool)(this["ShowSaveConfirmation"]));
            }
            set {
                this["ShowSaveConfirmation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ConfirmationSaveExportAndOpen {
            get {
                return ((bool)(this["ConfirmationSaveExportAndOpen"]));
            }
            set {
                this["ConfirmationSaveExportAndOpen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MaximizeOnOpen {
            get {
                return ((bool)(this["MaximizeOnOpen"]));
            }
            set {
                this["MaximizeOnOpen"] = value;
            }
        }
    }
}
